[project]
name = 'Artificial-Life-Simulation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.evolution-parameters]
path = 'contracts/evolution-parameters.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-life-form]
path = 'contracts/quantum-life-form.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
